/**
 * InterSystems IRIS FHIRAAS
 * Iris Api to manage tenants
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CreateTenant { 
    rootPassword?: string;
}
