/**
 * InterSystems IRIS FHIRAAS
 * Iris Api to manage tenants
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ServiceConfigData { 
    fhir_metadata_set?: string;
    fhir_version?: string;
    interactions_strategy_class?: string;
    default_search_page_size?: number;
    max_search_page_size?: number;
    max_search_results?: number;
    max_conditional_delete_results?: number;
    fhir_session_timeout?: number;
    default_prefer_handling?: string;
    debug_mode?: number;
}
